version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  prometheus-exporter:
    image: percona/mongodb_exporter:0.20
    container_name: prometheus-exporter
    ports:
      - "9216:9216"
      - "17001:17001"
    depends_on:
      - prometheus
    command:
      - "--mongodb.uri=mongodb://127.0.0.1:17001"
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
