server:
  port: 9000

spring:
  session:
    store-type: mongodb
    mongodb:
      collection-name: mySessions
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
      auto-index-creation: true
#  mvc:
#    log-request-details: true
management:
  endpoints:
    web:
      exposure:
        include: ["info", "prometheus","health", "metrics"]
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    git:
      enabled: true
      mode: full