server:
  port: 9000
spring:
  session:
    store-type: mongodb
    mongodb:
      collection-name: "mySessions"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/YaavArea"
#      auto-index-creation: true
      database: "YaavArea"
#  mvc:
#    log-request-details: true
management:
  endpoints:
    web:
      exposure:
        include: ["info", "prometheus","health", "metrics"]
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    git:
      enabled: true
      mode: full
logging:
  level:
    root: error
    com.yaavarea: trace
    web: error
springdoc:
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    syntax-highlight:
      theme: "obsidian"
