scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:9000']
        labels:
          application: 'My Spring Boot Application'
  - job_name: 'mongo_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9216']
        labels:
          application: 'My MongoDB'
